import { organizationRepositoriesList_organization_repositories_edges_node } from './types/organizationRepositoriesList'

export type RepositoryBasicInformation = organizationRepositoriesList_organization_repositories_edges_node
